Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Controller\\CodeCoverageController",
            "name": "CodeCoverageController",
            "summary": "",
            "url": "classes/App-Controller-CodeCoverageController.html"
        },                {
            "fqsen": "\\App\\Controller\\CodeCoverageController\u003A\u003AindexAction\u0028\u0029",
            "name": "indexAction",
            "summary": "",
            "url": "classes/App-Controller-CodeCoverageController.html#method_indexAction"
        },                {
            "fqsen": "\\App\\Controller\\DefaultController",
            "name": "DefaultController",
            "summary": "",
            "url": "classes/App-Controller-DefaultController.html"
        },                {
            "fqsen": "\\App\\Controller\\DefaultController\u003A\u003AindexAction\u0028\u0029",
            "name": "indexAction",
            "summary": "",
            "url": "classes/App-Controller-DefaultController.html#method_indexAction"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController",
            "name": "SecurityController",
            "summary": "",
            "url": "classes/App-Controller-SecurityController.html"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "",
            "url": "classes/App-Controller-SecurityController.html#method_login"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "",
            "url": "classes/App-Controller-SecurityController.html#method_register"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "",
            "url": "classes/App-Controller-SecurityController.html#method_logout"
        },                {
            "fqsen": "\\App\\Controller\\TaskController",
            "name": "TaskController",
            "summary": "",
            "url": "classes/App-Controller-TaskController.html"
        },                {
            "fqsen": "\\App\\Controller\\TaskController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controller-TaskController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\TaskController\u003A\u003AlistAction\u0028\u0029",
            "name": "listAction",
            "summary": "",
            "url": "classes/App-Controller-TaskController.html#method_listAction"
        },                {
            "fqsen": "\\App\\Controller\\TaskController\u003A\u003AlistDoneTasksAction\u0028\u0029",
            "name": "listDoneTasksAction",
            "summary": "",
            "url": "classes/App-Controller-TaskController.html#method_listDoneTasksAction"
        },                {
            "fqsen": "\\App\\Controller\\TaskController\u003A\u003AcreateAction\u0028\u0029",
            "name": "createAction",
            "summary": "",
            "url": "classes/App-Controller-TaskController.html#method_createAction"
        },                {
            "fqsen": "\\App\\Controller\\TaskController\u003A\u003AeditAction\u0028\u0029",
            "name": "editAction",
            "summary": "",
            "url": "classes/App-Controller-TaskController.html#method_editAction"
        },                {
            "fqsen": "\\App\\Controller\\TaskController\u003A\u003AtoggleTaskAction\u0028\u0029",
            "name": "toggleTaskAction",
            "summary": "",
            "url": "classes/App-Controller-TaskController.html#method_toggleTaskAction"
        },                {
            "fqsen": "\\App\\Controller\\TaskController\u003A\u003AdeleteTaskAction\u0028\u0029",
            "name": "deleteTaskAction",
            "summary": "",
            "url": "classes/App-Controller-TaskController.html#method_deleteTaskAction"
        },                {
            "fqsen": "\\App\\Controller\\TaskController\u003A\u003A\u0024security",
            "name": "security",
            "summary": "",
            "url": "classes/App-Controller-TaskController.html#property_security"
        },                {
            "fqsen": "\\App\\Controller\\TaskController\u003A\u003A\u0024tRepo",
            "name": "tRepo",
            "summary": "",
            "url": "classes/App-Controller-TaskController.html#property_tRepo"
        },                {
            "fqsen": "\\App\\Controller\\UserController",
            "name": "UserController",
            "summary": "",
            "url": "classes/App-Controller-UserController.html"
        },                {
            "fqsen": "\\App\\Controller\\UserController\u003A\u003AlistAction\u0028\u0029",
            "name": "listAction",
            "summary": "",
            "url": "classes/App-Controller-UserController.html#method_listAction"
        },                {
            "fqsen": "\\App\\Controller\\UserController\u003A\u003AcreateAction\u0028\u0029",
            "name": "createAction",
            "summary": "",
            "url": "classes/App-Controller-UserController.html#method_createAction"
        },                {
            "fqsen": "\\App\\Controller\\UserController\u003A\u003AeditAction\u0028\u0029",
            "name": "editAction",
            "summary": "",
            "url": "classes/App-Controller-UserController.html#method_editAction"
        },                {
            "fqsen": "\\App\\DataFixtures\\AppFixtures",
            "name": "AppFixtures",
            "summary": "",
            "url": "classes/App-DataFixtures-AppFixtures.html"
        },                {
            "fqsen": "\\App\\DataFixtures\\AppFixtures\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-DataFixtures-AppFixtures.html#method___construct"
        },                {
            "fqsen": "\\App\\DataFixtures\\AppFixtures\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/App-DataFixtures-AppFixtures.html#method_load"
        },                {
            "fqsen": "\\App\\Entity\\Task",
            "name": "Task",
            "summary": "",
            "url": "classes/App-Entity-Task.html"
        },                {
            "fqsen": "\\App\\Entity\\Task\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Task.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Task\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Task.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Task\u003A\u003AgetCreatedAt\u0028\u0029",
            "name": "getCreatedAt",
            "summary": "",
            "url": "classes/App-Entity-Task.html#method_getCreatedAt"
        },                {
            "fqsen": "\\App\\Entity\\Task\u003A\u003AsetCreatedAt\u0028\u0029",
            "name": "setCreatedAt",
            "summary": "",
            "url": "classes/App-Entity-Task.html#method_setCreatedAt"
        },                {
            "fqsen": "\\App\\Entity\\Task\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "",
            "url": "classes/App-Entity-Task.html#method_getTitle"
        },                {
            "fqsen": "\\App\\Entity\\Task\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "",
            "url": "classes/App-Entity-Task.html#method_setTitle"
        },                {
            "fqsen": "\\App\\Entity\\Task\u003A\u003AgetContent\u0028\u0029",
            "name": "getContent",
            "summary": "",
            "url": "classes/App-Entity-Task.html#method_getContent"
        },                {
            "fqsen": "\\App\\Entity\\Task\u003A\u003AsetContent\u0028\u0029",
            "name": "setContent",
            "summary": "",
            "url": "classes/App-Entity-Task.html#method_setContent"
        },                {
            "fqsen": "\\App\\Entity\\Task\u003A\u003A\u0024isDone",
            "name": "isDone",
            "summary": "",
            "url": "classes/App-Entity-Task.html#property_isDone"
        },                {
            "fqsen": "\\App\\Entity\\Task\u003A\u003Atoggle\u0028\u0029",
            "name": "toggle",
            "summary": "",
            "url": "classes/App-Entity-Task.html#method_toggle"
        },                {
            "fqsen": "\\App\\Entity\\Task\u003A\u003AgetUser\u0028\u0029",
            "name": "getUser",
            "summary": "",
            "url": "classes/App-Entity-Task.html#method_getUser"
        },                {
            "fqsen": "\\App\\Entity\\Task\u003A\u003AsetUser\u0028\u0029",
            "name": "setUser",
            "summary": "",
            "url": "classes/App-Entity-Task.html#method_setUser"
        },                {
            "fqsen": "\\App\\Entity\\Task\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Task.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Task\u003A\u003A\u0024createdAt",
            "name": "createdAt",
            "summary": "",
            "url": "classes/App-Entity-Task.html#property_createdAt"
        },                {
            "fqsen": "\\App\\Entity\\Task\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/App-Entity-Task.html#property_title"
        },                {
            "fqsen": "\\App\\Entity\\Task\u003A\u003A\u0024content",
            "name": "content",
            "summary": "",
            "url": "classes/App-Entity-Task.html#property_content"
        },                {
            "fqsen": "\\App\\Entity\\Task\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/App-Entity-Task.html#property_user"
        },                {
            "fqsen": "\\App\\Entity\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Entity-User.html"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-User.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetEmail\u0028\u0029",
            "name": "getEmail",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getEmail"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetEmail\u0028\u0029",
            "name": "setEmail",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setEmail"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetUserIdentifier\u0028\u0029",
            "name": "getUserIdentifier",
            "summary": "A\u0020visual\u0020identifier\u0020that\u0020represents\u0020this\u0020user.",
            "url": "classes/App-Entity-User.html#method_getUserIdentifier"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetUsername\u0028\u0029",
            "name": "getUsername",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getUsername"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetRoles\u0028\u0029",
            "name": "getRoles",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetRoles\u0028\u0029",
            "name": "setRoles",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getPassword"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetPassword\u0028\u0029",
            "name": "setPassword",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setPassword"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetSalt\u0028\u0029",
            "name": "getSalt",
            "summary": "Returning\u0020a\u0020salt\u0020is\u0020only\u0020needed,\u0020if\u0020you\u0020are\u0020not\u0020using\u0020a\u0020modern\nhashing\u0020algorithm\u0020\u0028e.g.\u0020bcrypt\u0020or\u0020sodium\u0029\u0020in\u0020your\u0020security.yaml.",
            "url": "classes/App-Entity-User.html#method_getSalt"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AeraseCredentials\u0028\u0029",
            "name": "eraseCredentials",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_eraseCredentials"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetUsername\u0028\u0029",
            "name": "setUsername",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setUsername"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetTasks\u0028\u0029",
            "name": "getTasks",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getTasks"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AaddTask\u0028\u0029",
            "name": "addTask",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_addTask"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AremoveTask\u0028\u0029",
            "name": "removeTask",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_removeTask"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AisAdmin\u0028\u0029",
            "name": "isAdmin",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_isAdmin"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_email"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024roles",
            "name": "roles",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_roles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_password"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024username",
            "name": "username",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_username"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024tasks",
            "name": "tasks",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_tasks"
        },                {
            "fqsen": "\\App\\Form\\TaskType",
            "name": "TaskType",
            "summary": "",
            "url": "classes/App-Form-TaskType.html"
        },                {
            "fqsen": "\\App\\Form\\TaskType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "",
            "url": "classes/App-Form-TaskType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\UserAdminType",
            "name": "UserAdminType",
            "summary": "",
            "url": "classes/App-Form-UserAdminType.html"
        },                {
            "fqsen": "\\App\\Form\\UserAdminType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "",
            "url": "classes/App-Form-UserAdminType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\UserType",
            "name": "UserType",
            "summary": "",
            "url": "classes/App-Form-UserType.html"
        },                {
            "fqsen": "\\App\\Form\\UserType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Form-UserType.html#method___construct"
        },                {
            "fqsen": "\\App\\Form\\UserType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "",
            "url": "classes/App-Form-UserType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\UserType\u003A\u003A\u0024authorization",
            "name": "authorization",
            "summary": "",
            "url": "classes/App-Form-UserType.html#property_authorization"
        },                {
            "fqsen": "\\App\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Kernel.html"
        },                {
            "fqsen": "\\App\\Kernel\u003A\u003AconfigureContainer\u0028\u0029",
            "name": "configureContainer",
            "summary": "",
            "url": "classes/App-Kernel.html#method_configureContainer"
        },                {
            "fqsen": "\\App\\Kernel\u003A\u003AconfigureRoutes\u0028\u0029",
            "name": "configureRoutes",
            "summary": "",
            "url": "classes/App-Kernel.html#method_configureRoutes"
        },                {
            "fqsen": "\\App\\Repository\\TaskRepository",
            "name": "TaskRepository",
            "summary": "",
            "url": "classes/App-Repository-TaskRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\TaskRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-TaskRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\TaskRepository\u003A\u003AfindByIsDone\u0028\u0029",
            "name": "findByIsDone",
            "summary": "",
            "url": "classes/App-Repository-TaskRepository.html#method_findByIsDone"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository",
            "name": "UserRepository",
            "summary": "",
            "url": "classes/App-Repository-UserRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-UserRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Security\\AppAuthenticator",
            "name": "AppAuthenticator",
            "summary": "",
            "url": "classes/App-Security-AppAuthenticator.html"
        },                {
            "fqsen": "\\App\\Security\\AppAuthenticator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Security-AppAuthenticator.html#method___construct"
        },                {
            "fqsen": "\\App\\Security\\AppAuthenticator\u003A\u003Aauthenticate\u0028\u0029",
            "name": "authenticate",
            "summary": "",
            "url": "classes/App-Security-AppAuthenticator.html#method_authenticate"
        },                {
            "fqsen": "\\App\\Security\\AppAuthenticator\u003A\u003AonAuthenticationSuccess\u0028\u0029",
            "name": "onAuthenticationSuccess",
            "summary": "",
            "url": "classes/App-Security-AppAuthenticator.html#method_onAuthenticationSuccess"
        },                {
            "fqsen": "\\App\\Security\\AppAuthenticator\u003A\u003AgetLoginUrl\u0028\u0029",
            "name": "getLoginUrl",
            "summary": "",
            "url": "classes/App-Security-AppAuthenticator.html#method_getLoginUrl"
        },                {
            "fqsen": "\\App\\Security\\AppAuthenticator\u003A\u003ALOGIN_ROUTE",
            "name": "LOGIN_ROUTE",
            "summary": "",
            "url": "classes/App-Security-AppAuthenticator.html#constant_LOGIN_ROUTE"
        },                {
            "fqsen": "\\App\\Security\\AppAuthenticator\u003A\u003A\u0024urlGenerator",
            "name": "urlGenerator",
            "summary": "",
            "url": "classes/App-Security-AppAuthenticator.html#property_urlGenerator"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "namespaces/app-controller.html"
        },                {
            "fqsen": "\\App\\DataFixtures",
            "name": "DataFixtures",
            "summary": "",
            "url": "namespaces/app-datafixtures.html"
        },                {
            "fqsen": "\\App\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/app-entity.html"
        },                {
            "fqsen": "\\App\\Form",
            "name": "Form",
            "summary": "",
            "url": "namespaces/app-form.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Repository",
            "name": "Repository",
            "summary": "",
            "url": "namespaces/app-repository.html"
        },                {
            "fqsen": "\\App\\Security",
            "name": "Security",
            "summary": "",
            "url": "namespaces/app-security.html"
        }            ]
);
